language: python
python:
  - "2.7"
install:
  - make deps
script:
  - make lint
  - make test
  - sudo make docker_build
  - make docker run
  - sleep 3; make test_api


after_success:

  - sudo make docker_push



services:
  - docker
deploy:
  provider: heroku
  app: sheltered-atoll-12700
  api_key: ${HEROKU_API_KEY}
